ITGWRP-1930 Added reconnection handling for SyslogTcpWriter64k. Open …
Hapag-Lloyd/log4j-syslogwriter-64k pull request #13
Opened 2021-01-13 12:36 UTC by LasseGosch

2021-01-13 16:32 UTC, lars-sh commented
I'd expect to use no retries, but resetting the writer and rethrowing the original IOException. That even simplifies the code a lot and does not require sleeps. The outer code can handle the error accordingly. Example:

```
} catch (IOException) {
    close();
    throw e;
}
```

And inside the close method you could reset the socket and writer fields to `Optional.empty()`.

2021-01-14 09:25 UTC, lars-sh requested changes

2021-01-14 09:25 UTC, lars-sh commented on log4jSyslogWriter64k/src/main/java/com/github/loggly/log4j/helpers/SyslogTcpWriter64k.java
> +		socket = Optional.empty();
Please do this in a finally block as there might occur additional IOExceptions in error cases.

2021-01-14 09:25 UTC, lars-sh commented on log4jSyslogWriter64k/src/main/java/com/github/loggly/log4j/helpers/SyslogTcpWriter64k.java
> +			close();
This should probably be wrapped in a try-catch, ignoring IOExceptions coming from the close method to make sure, exceptions inside the close method do not hide the original IOException from here.

2021-01-14 15:52 UTC, lars-sh approved these changes

2021-01-14 15:52 UTC, lars-sh commented
@noxone, please review and approve this PR, esp. the synchronized handling. Thanks :)

2021-01-14 16:22 UTC, noxone approved these changes

2021-01-15 12:32 UTC, merged